/**
 * Database types - These would typically be generated by Supabase CLI
 * Run: npx supabase gen types typescript --local > src/types/database.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      clients: {
        Row: {
          id: string;
          name: string;
          hubspot_company_id: string | null;
          contract_renewal_date: string | null;
          contract_value: number | null;
          primary_contact_email: string | null;
          status: "active" | "churned" | "prospect";
          created_at: string;
          updated_at: string;
          created_by: string;
        };
        Insert: {
          id?: string;
          name: string;
          hubspot_company_id?: string | null;
          contract_renewal_date?: string | null;
          contract_value?: number | null;
          primary_contact_email?: string | null;
          status?: "active" | "churned" | "prospect";
          created_at?: string;
          updated_at?: string;
          created_by: string;
        };
        Update: {
          id?: string;
          name?: string;
          hubspot_company_id?: string | null;
          contract_renewal_date?: string | null;
          contract_value?: number | null;
          primary_contact_email?: string | null;
          status?: "active" | "churned" | "prospect";
          created_at?: string;
          updated_at?: string;
          created_by?: string;
        };
      };
      initiatives: {
        Row: {
          id: string;
          client_id: string;
          title: string;
          description: string | null;
          status: "not_started" | "in_progress" | "completed" | "on_hold";
          priority: "low" | "medium" | "high" | "critical";
          due_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          title: string;
          description?: string | null;
          status?: "not_started" | "in_progress" | "completed" | "on_hold";
          priority?: "low" | "medium" | "high" | "critical";
          due_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          title?: string;
          description?: string | null;
          status?: "not_started" | "in_progress" | "completed" | "on_hold";
          priority?: "low" | "medium" | "high" | "critical";
          due_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      risks: {
        Row: {
          id: string;
          client_id: string;
          title: string;
          description: string | null;
          severity: "low" | "medium" | "high" | "critical";
          status: "open" | "mitigated" | "resolved";
          mitigation_plan: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          title: string;
          description?: string | null;
          severity?: "low" | "medium" | "high" | "critical";
          status?: "open" | "mitigated" | "resolved";
          mitigation_plan?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          title?: string;
          description?: string | null;
          severity?: "low" | "medium" | "high" | "critical";
          status?: "open" | "mitigated" | "resolved";
          mitigation_plan?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      weekly_updates: {
        Row: {
          id: string;
          client_id: string;
          week_start_date: string;
          overall_health: "green" | "yellow" | "red";
          health_rationale: string | null;
          summary: string;
          wins: string | null;
          blockers: string | null;
          next_steps: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          week_start_date: string;
          overall_health: "green" | "yellow" | "red";
          health_rationale?: string | null;
          summary: string;
          wins?: string | null;
          blockers?: string | null;
          next_steps?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          week_start_date?: string;
          overall_health?: "green" | "yellow" | "red";
          health_rationale?: string | null;
          summary?: string;
          wins?: string | null;
          blockers?: string | null;
          next_steps?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      jira_rollup_snapshots: {
        Row: {
          id: string;
          client_id: string;
          snapshot_date: string;
          total_issues: number;
          open_issues: number;
          in_progress_issues: number;
          completed_issues: number;
          overdue_issues: number;
          data_json: Json;
          created_at: string;
          synced_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          snapshot_date: string;
          total_issues?: number;
          open_issues?: number;
          in_progress_issues?: number;
          completed_issues?: number;
          overdue_issues?: number;
          data_json?: Json;
          created_at?: string;
          synced_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          snapshot_date?: string;
          total_issues?: number;
          open_issues?: number;
          in_progress_issues?: number;
          completed_issues?: number;
          overdue_issues?: number;
          data_json?: Json;
          created_at?: string;
          synced_at?: string;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: "admin" | "standard" | "exec_viewer";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: "admin" | "standard" | "exec_viewer";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: "admin" | "standard" | "exec_viewer";
          created_at?: string;
          updated_at?: string;
        };
      };
      integration_configs: {
        Row: {
          id: string;
          integration_type: "jira" | "hubspot";
          config_json: Json;
          is_active: boolean;
          last_synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          integration_type: "jira" | "hubspot";
          config_json: Json;
          is_active?: boolean;
          last_synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          integration_type?: "jira" | "hubspot";
          config_json?: Json;
          is_active?: boolean;
          last_synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      client_status: "active" | "churned" | "prospect";
      health_status: "green" | "yellow" | "red";
      initiative_status: "not_started" | "in_progress" | "completed" | "on_hold";
      integration_type: "jira" | "hubspot";
      priority_level: "low" | "medium" | "high" | "critical";
      risk_severity: "low" | "medium" | "high" | "critical";
      risk_status: "open" | "mitigated" | "resolved";
      user_role: "admin" | "standard" | "exec_viewer";
    };
  };
};

// Convenience type aliases
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
